/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author fernando
 */
public class JfrmMain extends javax.swing.JFrame {

    /**
     * Creates new form JfrmMain
     */
    public JfrmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_update1 = new javax.swing.JButton();
        jbtn_ingresar = new javax.swing.JButton();
        jbtn_update = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_verEstrenos = new javax.swing.JButton();
        jbtn_verPorFecha = new javax.swing.JButton();
        jbtn_verTablaUno = new javax.swing.JButton();
        jbtn_verTablaDos = new javax.swing.JButton();
        jbtn_Salir = new javax.swing.JButton();

        jbtn_update1.setText("Modificar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtn_ingresar.setText("Ingresa");
        jbtn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ingresarActionPerformed(evt);
            }
        });

        jbtn_update.setText("Modificar");
        jbtn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_updateActionPerformed(evt);
            }
        });

        jbtn_eliminar.setText("Eliminar");
        jbtn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_eliminarActionPerformed(evt);
            }
        });

        jbtn_verEstrenos.setText("Ver Estrenos");
        jbtn_verEstrenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_verEstrenosActionPerformed(evt);
            }
        });

        jbtn_verPorFecha.setText("Ver por fecha");
        jbtn_verPorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_verPorFechaActionPerformed(evt);
            }
        });

        jbtn_verTablaUno.setText("Ver Tabla 1");
        jbtn_verTablaUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_verTablaUnoActionPerformed(evt);
            }
        });

        jbtn_verTablaDos.setText("Ver Tabla 2");
        jbtn_verTablaDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_verTablaDosActionPerformed(evt);
            }
        });

        jbtn_Salir.setText("Salir");
        jbtn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtn_verPorFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_verEstrenos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_verTablaUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_verTablaDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jbtn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_ingresar)
                    .addComponent(jbtn_verEstrenos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_update)
                    .addComponent(jbtn_verPorFecha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_eliminar)
                    .addComponent(jbtn_verTablaUno))
                .addGap(18, 18, 18)
                .addComponent(jbtn_verTablaDos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_Salir)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ingresarActionPerformed
        // TODO add your handling code here:
        new JfrmIngresar().setVisible(true);
                
    }//GEN-LAST:event_jbtn_ingresarActionPerformed

    private void jbtn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_updateActionPerformed
        // TODO add your handling code here:
        new JfrmUpdate().setVisible(true);
    }//GEN-LAST:event_jbtn_updateActionPerformed

    private void jbtn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_eliminarActionPerformed
        // TODO add your handling code here:
        new JfrmDelete().setVisible(true);
    }//GEN-LAST:event_jbtn_eliminarActionPerformed

    private void jbtn_verEstrenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_verEstrenosActionPerformed
        // TODO add your handling code here:
        new JfrmReadEstreno().setVisible(true);
    }//GEN-LAST:event_jbtn_verEstrenosActionPerformed

    private void jbtn_verPorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_verPorFechaActionPerformed
        // TODO add your handling code here:
        new JfrmReadPorDate().setVisible(true);
    }//GEN-LAST:event_jbtn_verPorFechaActionPerformed

    private void jbtn_verTablaUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_verTablaUnoActionPerformed
        // TODO add your handling code here:
        new JfrmVerTablaUno().setVisible(true);
    }//GEN-LAST:event_jbtn_verTablaUnoActionPerformed

    private void jbtn_verTablaDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_verTablaDosActionPerformed
        // TODO add your handling code here:
        new JfrmVerTablaDos().setVisible(true);
    }//GEN-LAST:event_jbtn_verTablaDosActionPerformed

    private void jbtn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_SalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtn_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_Salir;
    private javax.swing.JButton jbtn_eliminar;
    private javax.swing.JButton jbtn_ingresar;
    private javax.swing.JButton jbtn_update;
    private javax.swing.JButton jbtn_update1;
    private javax.swing.JButton jbtn_verEstrenos;
    private javax.swing.JButton jbtn_verPorFecha;
    private javax.swing.JButton jbtn_verTablaDos;
    private javax.swing.JButton jbtn_verTablaUno;
    // End of variables declaration//GEN-END:variables
}
